name: Deploy to Production

on:
  push:
    branches: [production]
  pull_request:
    branches: [production]

env:
  SERVER_IP: ${{ secrets.PROD_SERVER_IP }}
  SSH_USER: ${{ secrets.PROD_SSH_USER }}
  SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
  BACKEND_DIR: /var/www/project/backend
  FRONTEND_DIR: /var/www/project/frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Забираем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create folders
        run: mkdir -p frontend backend

      # Шаг 2: Собираем фронтенд
      - name: Build Frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      # Шаг 3: Устанавливаем зависимости бэкенда
      - name: Install Backend Dependencies
        working-directory: backend
        run: npm ci --production

      # Шаг 4: Копируем файлы на сервер через SSH
      - name: Deploy Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          source: |
            frontend/dist/*
            backend/*
          target: |
            ${{ env.FRONTEND_DIR }}
            ${{ env.BACKEND_DIR }}

      # Шаг 5: Запускаем команды на сервере через SSH
      - name: Restart Services
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          script: |
            cd ${{ env.BACKEND_DIR }}
            npm install --production
            pm2 restart ecosystem.config.js
            sudo systemctl restart nginx
