name: Deploy to Production

on:
  push:
    branches: [production]
  pull_request:
    branches: [production]

env:
  SERVER_IP: ${{ secrets.PROD_SERVER_IP }}
  SSH_USER: ${{ secrets.PROD_SSH_USER }}
  SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
  FRONTEND_DIR: /var/www/project

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Забираем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Собираем фронтенд
      - name: Build Frontend
        run: |
          npm ci
          npm run build

      - name: List built files
        run: ls -R dist

      # Шаг 4: Копируем файлы на сервер через SSH
      - name: Deploy Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          source: |
            dist/*
          target: |
            ${{ env.FRONTEND_DIR }}
          strip_components: 1

      - name: Restart nginx
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          script: |
            sudo systemctl restart nginx
